# -*- coding: utf-8 -*-
"""AI_NLP_ASS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZxTaJM9RLBR2IkmHI9tAnnjfDTIm1q7
"""

!pip install nltk

import nltk

nltk.download("punkt")

"""# **TAKING INPUT**"""

sent = " i will walk 500 miles . I will eat"

sent

"""# **TOKENIZATION**"""

from nltk import word_tokenize , sent_tokenize

words = word_tokenize(sent)

print(words)

sentences = sent_tokenize(sent)

print(sentences)

"""# **STOPWORDS**"""

from nltk.corpus import stopwords

nltk.download('stopwords')

stopwords

stopwords = stopwords.words("english")

print(stopwords)

for j in stopwords:
  if j in words:
    words.remove(j)
    print(words)

"""# **STEMING**"""

from nltk import PorterStemmer

mystemmer = PorterStemmer()

print(words)

stemmed_words = [mystemmer.stem(word) for word in words]

print(stemmed_words)

"""
# **COUNTING WORDS**"""

from collections import Counter

count_dict = {}

count_dict = Counter(stemmed_words) #easy syntax

print(count_dict)

"""for word in stemmed_words:    #complex syntax
  if word in count_dict:
    count_dict[word] += 1
  else:
    count_dict[word] = 1

print(count_dict)

# **PART OF SPEECH TAGGING**
"""

from nltk import pos_tag

nltk.download('averaged_perceptron_tagger')

pos_tagged = pos_tag(stemmed_words)

print(pos_tagged)

counting_pos_tags =Counter(entry[1] for entry in pos_tagged)

print(counting_pos_tags)

