# -*- coding: utf-8 -*-
"""tower_of_hanoi_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UB0AN09_btyCL9KYD574gPKI_cCj9zBP
"""

def move_disk(disk, source, destination):
    print(f"Move disk {disk} from {source} to {destination}")

def tower_of_hanoi(disks, source, auxiliary, destination):
    if disks == 1:
        move_disk(disks, source, destination)
        return
    tower_of_hanoi(disks - 1, source, destination, auxiliary)
    move_disk(disks, source, destination)
    tower_of_hanoi(disks - 1, auxiliary, source, destination)

disks = 3
source, auxiliary, destination = 'A', 'B', 'C'
print(f"Solution for Tower of Hanoi with {disks} disks:")
tower_of_hanoi(disks, source, auxiliary, destination)

